<?php
/**
 * @file
 * Code for the cosbi contact feature.
 */

include_once 'cosbi_contact.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cosbi_contact_form_contact_node_form_alter(&$form, &$form_state) {

  // Hide field_contact_role and pull in url arg to populate it.
  //if (!(user_access('edit any contact content'))) {
    //$form['field_contact_role']['#access'] = FALSE;
  //}
  $contact_role_vocab = taxonomy_vocabulary_machine_name_load('contact_role');
  $roles = entity_load('taxonomy_term', FALSE, array('vid' => $contact_role_vocab->vid));
  $contact_roles = array();
  foreach ($roles as $role) {
    $contact_roles[strtolower(str_replace(' ', '-', $role->name))] = $role->tid;
  }

  if (array_key_exists(arg(3), $contact_roles)) {
    //drupal_set_title('Create arg(3)');
    $form['field_contact_role'][LANGUAGE_NONE]['#default_value'] = array($contact_roles[arg(3)]);
  }
}